name: Tests
on: [push]
jobs:
  Test-Canvas-Package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.2'

      - name: Run canvas test
        run: go test backend/internal/canvas

      - name: Run telegram_initdata_authentication test
        run: go test backend/internal/authentication/telegram_init_data
