name: Tests
on: [push]
jobs:
  Test-Canvas-Package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.2'

      - name: Build test
        run: go test -c -o out/backend_canvas.test backend/canvas

      - name: Run Test
        run: ./out/backend_canvas.test